services:
  - type: web
    name: kisangpt
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: DATAGOV_API_KEY
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: DATAGOV_BASE_URL
        value: https://api.data.gov.in
      - key: DATAGOV_VERIFY_SSL
        value: "true"
      - key: MODEL_NAME
        value: gemini-2.0-flash-exp
      - key: LOG_LEVEL
        value: INFO
      - key: DEBUG
        value: "false"
      - key: CACHE_TTL_MINUTES
        value: "60"
      - key: WEATHER_REFRESH_INTERVAL
        value: "60"
      - key: MARKET_REFRESH_INTERVAL
        value: "120"
      - key: CROP_REFRESH_INTERVAL
        value: "1440"
